name: ad_exchange_pred
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - lightgbm
  - mlflow
  - pyyaml
  - polars
  - pip:
    - shap