# configs/config.yaml

data_paths:
  train_file: 'data/train_data.csv'
  test_file: 'data/test_data.csv'
  results_folder: 'results/'
  model_save_path: 'models/trained_model.pkl'

parameters:
  benchmark_f1: 0.503
  neg_ratio: 4.919339318126806 # Tuned
  sampling: False
  check_feature_importance: False

model_parameters: # Tuned
  objective: 'binary'
  metric: 'f1'
  verbose: -1
  random_state: 23
  boosting_type: 'gbdt'
  n_estimators: 500
  learning_rate: 0.05601405924916412
  max_depth: 6
  num_leaves: 35
  subsample: 0.8903345089717967
  lambda_l2: 0.00031416100090784403
  
training_parameters:
  do_oversampling: False
  do_crossvalidation: False
  n_splits: 5
  shuffle: True
  random_state: 23
  scoring: 'f1'
  multiplier: 1.5  # to calculate UP_RATIO
