# configs/model_config.yaml

data_paths:
  train_file: 'data/train_data.csv'
  test_file: 'data/test_data.csv'
  results_folder: 'results/'
  model_save_path: 'models/trained_model.pkl'

parameters:
  benchmark_f1: 0.503
  neg_ratio: 5     # 5 For full train
  sampling: False
  check_feature_importance: True

model_parameters:
  objective: 'binary'
  metric: 'f1'
  verbose: -1
  random_state: 23
  boosting_type: 'gbdt'
  n_estimators: 200

training_parameters:
  do_oversampling: False
  do_crossvalidation: True
  n_splits: 5
  shuffle: True
  random_state: 23
  scoring: 'f1'
  multiplier: 1.5  # to calculate UP_RATIO